# DO NOT CHANGE THIS FILE. Only change the IMAGE_NAME (__APP_NAME__) variable.
name: test and build image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sirlegendary/gitea-custom-runner:latest
    env:
      REGISTRY_HOST: ghcr.io # Do not change this
      IMAGE_NAME: sirlegendary/__APP_NAME__:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -e ".[dev]"

      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:latest
          secrets: |
            "INTERMEDIATE_CA_BUNDLE=${{ secrets.INTERMEDIATE_CA_BUNDLE }}"
